import {
  WorkingTable,
  type WorkingAssignmentRow,
} from "@/components/admin/working-table";

export const workingAssignments: WorkingAssignmentRow[] = [
  {
    id: "1",
    name: "Product Launch Presentation",
    user: "emma.wilson",
    assignmentType: "Presentation",
    status: "doing",
    isPaid: false,
    deliveryDate: "2026-06-18T00:00:00Z",
    providedAt: null,
    addedBy: "nishant",
  },
  {
    id: "2",
    name: "Leadership Reflection Essay",
    user: "yuki.tanaka",
    assignmentType: "Essay",
    status: "doing",
    isPaid: true,
    deliveryDate: "2026-06-08T00:00:00Z",
    providedAt: null,
    addedBy: "aarya",
  },
  {
    id: "3",
    name: "Machine Learning Essay",
    user: "noah.smith",
    assignmentType: "Essay",
    status: "doing",
    isPaid: true,
    deliveryDate: "2026-06-30T00:00:00Z",
    providedAt: null,
    addedBy: "bhupendra",
  },
  {
    id: "4",
    name: "Investor Update Presentation",
    user: "mia.johnson",
    assignmentType: "Presentation",
    status: "doing",
    isPaid: true,
    deliveryDate: "2026-06-27T00:00:00Z",
    providedAt: null,
    addedBy: "nishant",
  },
  {
    id: "5",
    name: "UX Research Project",
    user: "li.wei",
    assignmentType: "Project",
    status: "pending",
    isPaid: false,
    deliveryDate: "2026-06-25T00:00:00Z",
    providedAt: null,
    addedBy: "aarya",
  },
  {
    id: "6",
    name: "Financial Analysis Report",
    user: "alex.kumar",
    assignmentType: "Report",
    status: "review",
    isPaid: true,
    deliveryDate: "2026-06-02T00:00:00Z",
    providedAt: "2026-05-30T09:15:00Z",
    addedBy: "bhupendra",
  },
  {
    id: "7",
    name: "Quarterly Sales Report",
    user: "olivia.brown",
    assignmentType: "Report",
    status: "review",
    isPaid: true,
    deliveryDate: "2026-06-14T00:00:00Z",
    providedAt: "2026-06-12T08:30:00Z",
    addedBy: "nishant",
  },
  {
    id: "8",
    name: "Brand Identity Project",
    user: "lucas.silva",
    assignmentType: "Project",
    status: "review",
    isPaid: true,
    deliveryDate: "2026-06-11T00:00:00Z",
    providedAt: "2026-06-09T10:12:00Z",
    addedBy: "aarya",
  },
  {
    id: "9",
    name: "Startup Pitch Deck",
    user: "ahmed.hassan",
    assignmentType: "Presentation",
    status: "pending",
    isPaid: false,
    deliveryDate: "2026-06-22T00:00:00Z",
    providedAt: null,
    addedBy: "bhupendra",
  },
  {
    id: "10",
    name: "Operations Audit Report",
    user: "priya.sharma",
    assignmentType: "Report",
    status: "pending",
    isPaid: false,
    deliveryDate: "2026-07-04T00:00:00Z",
    providedAt: null,
    addedBy: "nishant",
  },
];

export default function WorkingPage() {
  return (
    <div className="flex h-full min-h-0 flex-col pt-2">
      <WorkingTable assignments={workingAssignments} />
    </div>
  );
}
