export const endpoints = {
  login: "/api/admin/auth/login/",
  totpSetup: "/api/admin/auth/totp/setup/",
  totpVerify: "/api/admin/auth/totp/verify/",
  me: "/api/admin/auth/me/",
  refresh: "/api/admin/auth/refresh-token/",
  logout: "/api/admin/auth/logout/",
  dashboard: "/api/admin/dashboard/",
  calendar: "/api/admin/calendar/",
  calendarMarkBusy: "/api/admin/calendar/mark-busy/",
  calendarMarkAvailable: "/api/admin/calendar/mark-available/",
  users: "/api/admin/users/",
  usersSearch: "/api/admin/users/search/",
  usersDelete: "/api/admin/users/delete/",
  usersUpdatePassword: "/api/admin/users/update-password/",
  userDetails: (userId: string) => `/api/admin/users/${userId}/`,
  userAssignments: (userId: string) =>
    `/api/admin/users/${userId}/assignments/`,
  assignments: "/api/admin/assignments/",
  assignmentsDelete: "/api/admin/assignments/delete/",
  assignmentsAddOnWorking: "/api/admin/assignments/add-on-working/",
  assignmentProgress: (assignmentId: string) =>
    `/api/admin/assignments/${assignmentId}/progress/`,
  assignmentProgressReceived: "/api/admin/assignments/progress/received/",
  assignmentProgressPayment: "/api/admin/assignments/progress/payment/",
  assignmentProgressDoing: "/api/admin/assignments/progress/doing/",
  assignmentProgressCompleted: "/api/admin/assignments/progress/completed/",
  working: "/api/admin/working/",
  workingRemove: "/api/admin/working/remove/",
  badges: "/api/admin/badges/",
  notifications: "/api/admin/notifications/",
  notificationsCreate: "/api/admin/notifications/create/",
  notificationsResend: "/api/admin/notifications/resend/",
} as const;
