import {
  AssignmentsTable,
  type AssignmentRow,
} from "@/components/admin/assignments-table";

export const assignments: AssignmentRow[] = [
  {
    id: "1",
    name: "Marketing Strategy Essay",
    user: "sophie.martin",
    assignmentType: "Essay",
    status: "completed",
    isPaid: true,
    deliveryDate: "2026-05-12T00:00:00Z",
    providedAt: "2026-05-10T14:20:00Z",
  },
  {
    id: "2",
    name: "Financial Analysis Report",
    user: "alex.kumar",
    assignmentType: "Report",
    status: "review",
    isPaid: true,
    deliveryDate: "2026-06-02T00:00:00Z",
    providedAt: "2026-05-30T09:15:00Z",
  },
  {
    id: "3",
    name: "Product Launch Presentation",
    user: "emma.wilson",
    assignmentType: "Presentation",
    status: "doing",
    isPaid: false,
    deliveryDate: "2026-06-18T00:00:00Z",
    providedAt: null,
  },
  {
    id: "4",
    name: "UX Research Project",
    user: "li.wei",
    assignmentType: "Project",
    status: "pending",
    isPaid: false,
    deliveryDate: "2026-06-25T00:00:00Z",
    providedAt: null,
  },
  {
    id: "5",
    name: "Business Ethics Case Study",
    user: "marco.rossi",
    assignmentType: "Case Study",
    status: "completed",
    isPaid: true,
    deliveryDate: "2026-04-28T00:00:00Z",
    providedAt: "2026-04-26T11:40:00Z",
  },
  {
    id: "6",
    name: "Data Science Capstone",
    user: "nina.petersen",
    assignmentType: "Project",
    status: "rejected",
    isPaid: false,
    deliveryDate: "2026-05-05T00:00:00Z",
    providedAt: "2026-05-03T16:05:00Z",
  },
  {
    id: "7",
    name: "Leadership Reflection Essay",
    user: "yuki.tanaka",
    assignmentType: "Essay",
    status: "doing",
    isPaid: true,
    deliveryDate: "2026-06-08T00:00:00Z",
    providedAt: null,
  },
  {
    id: "8",
    name: "Quarterly Sales Report",
    user: "olivia.brown",
    assignmentType: "Report",
    status: "review",
    isPaid: true,
    deliveryDate: "2026-06-14T00:00:00Z",
    providedAt: "2026-06-12T08:30:00Z",
  },
  {
    id: "9",
    name: "Startup Pitch Deck",
    user: "ahmed.hassan",
    assignmentType: "Presentation",
    status: "pending",
    isPaid: false,
    deliveryDate: "2026-06-22T00:00:00Z",
    providedAt: null,
  },
  {
    id: "10",
    name: "Supply Chain Case Study",
    user: "isabella.gomez",
    assignmentType: "Case Study",
    status: "completed",
    isPaid: true,
    deliveryDate: "2026-05-20T00:00:00Z",
    providedAt: "2026-05-18T13:55:00Z",
  },
  {
    id: "11",
    name: "Machine Learning Essay",
    user: "noah.smith",
    assignmentType: "Essay",
    status: "doing",
    isPaid: true,
    deliveryDate: "2026-06-30T00:00:00Z",
    providedAt: null,
  },
  {
    id: "12",
    name: "Operations Audit Report",
    user: "priya.sharma",
    assignmentType: "Report",
    status: "pending",
    isPaid: false,
    deliveryDate: "2026-07-04T00:00:00Z",
    providedAt: null,
  },
  {
    id: "13",
    name: "Brand Identity Project",
    user: "lucas.silva",
    assignmentType: "Project",
    status: "review",
    isPaid: true,
    deliveryDate: "2026-06-11T00:00:00Z",
    providedAt: "2026-06-09T10:12:00Z",
  },
  {
    id: "14",
    name: "Healthcare Policy Essay",
    user: "hannah.becker",
    assignmentType: "Essay",
    status: "completed",
    isPaid: true,
    deliveryDate: "2026-04-15T00:00:00Z",
    providedAt: "2026-04-13T17:25:00Z",
  },
  {
    id: "15",
    name: "Mobile App Case Study",
    user: "daniel.kim",
    assignmentType: "Case Study",
    status: "rejected",
    isPaid: false,
    deliveryDate: "2026-05-08T00:00:00Z",
    providedAt: "2026-05-06T12:48:00Z",
  },
  {
    id: "16",
    name: "Investor Update Presentation",
    user: "mia.johnson",
    assignmentType: "Presentation",
    status: "doing",
    isPaid: true,
    deliveryDate: "2026-06-27T00:00:00Z",
    providedAt: null,
  },
];

export default function AssignmentsPage() {
  return (
    <div className="flex h-full min-h-0 flex-col pt-2">
      <AssignmentsTable assignments={assignments} />
    </div>
  );
}
