import { UsersTable, type UserRow } from "@/components/admin/users-table";

const users: UserRow[] = [
  {
    id: "1",
    username: "jane.doe",
    role: "Admin",
    country: "United States",
    isActive: true,
    isSuspended: false,
    createdAt: "2025-11-12T09:15:00Z",
  },
  {
    id: "2",
    username: "alex.kumar",
    role: "Mentor",
    country: "India",
    isActive: true,
    isSuspended: false,
    createdAt: "2025-12-03T14:22:00Z",
  },
  {
    id: "3",
    username: "sophie.martin",
    role: "Student",
    country: "France",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-01-08T11:40:00Z",
  },
  {
    id: "4",
    username: "li.wei",
    role: "Student",
    country: "Singapore",
    isActive: false,
    isSuspended: true,
    createdAt: "2026-01-19T08:05:00Z",
  },
  {
    id: "5",
    username: "marco.rossi",
    role: "Mentor",
    country: "Italy",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-02-01T16:18:00Z",
  },
  {
    id: "6",
    username: "emma.wilson",
    role: "Student",
    country: "United Kingdom",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-02-14T10:30:00Z",
  },
  {
    id: "7",
    username: "carlos.lopez",
    role: "Admin",
    country: "Spain",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-02-22T13:12:00Z",
  },
  {
    id: "8",
    username: "nina.petersen",
    role: "Student",
    country: "Denmark",
    isActive: false,
    isSuspended: false,
    createdAt: "2026-03-04T07:55:00Z",
  },
  {
    id: "9",
    username: "yuki.tanaka",
    role: "Mentor",
    country: "Japan",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-03-11T18:44:00Z",
  },
  {
    id: "10",
    username: "olivia.brown",
    role: "Student",
    country: "Canada",
    isActive: true,
    isSuspended: true,
    createdAt: "2026-03-18T09:28:00Z",
  },
  {
    id: "11",
    username: "ahmed.hassan",
    role: "Student",
    country: "Egypt",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-03-25T12:06:00Z",
  },
  {
    id: "12",
    username: "isabella.gomez",
    role: "Mentor",
    country: "Mexico",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-04-02T15:33:00Z",
  },
  {
    id: "13",
    username: "noah.smith",
    role: "Student",
    country: "Australia",
    isActive: false,
    isSuspended: true,
    createdAt: "2026-04-09T06:50:00Z",
  },
  {
    id: "14",
    username: "priya.sharma",
    role: "Admin",
    country: "India",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-04-16T19:17:00Z",
  },
  {
    id: "15",
    username: "lucas.silva",
    role: "Student",
    country: "Brazil",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-04-23T08:41:00Z",
  },
  {
    id: "16",
    username: "hannah.becker",
    role: "Mentor",
    country: "Germany",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-05-01T11:25:00Z",
  },
  {
    id: "17",
    username: "daniel.kim",
    role: "Student",
    country: "South Korea",
    isActive: true,
    isSuspended: false,
    createdAt: "2026-05-08T14:09:00Z",
  },
  {
    id: "18",
    username: "mia.johnson",
    role: "Student",
    country: "United States",
    isActive: false,
    isSuspended: false,
    createdAt: "2026-05-15T17:52:00Z",
  },
];

export default function UsersPage() {
  return (
    <div className="flex h-full min-h-0 flex-col pt-2">
      <UsersTable users={users} />
    </div>
  );
}
